package kr.co.korea.error;

/**
 * Created by ideapad on 2016-02-25.
 */
public enum ErrorType {
    NORMAL(0.0),
    BATTERY_LIFE(2.0),
    BATTERY_LOW(5.0),
    BATTERY_DEAD(10.0),
    MOTOR_BALANCE_PASSING_ERROR(1.0),
    MOTOR_BALANCE_CONTINUOUS_ERROR(5.0),
    MOTOR_BALANCE_PERMANENT_ERROR(10.0),
    MOTOR_RPM_PASSING_ERROR(1.0),
    MOTOR_RPM_CONTINUOUS_ERROR(5.0),
    MOTOR_RPM_PERMANENT_ERROR(10.0),
    SENSOR_GPS_PASSING_ERROR(1.0),
    SENSOR_GPS_CONTINUOUS_ERROR(5.0),
    SENSOR_GPS_PERMANENT_ERROR(10.0),
    SENSOR_GYRO_PASSING_ERROR(1.0),
    SENSOR_GYRO_CONTINUOUS_ERROR(5.0),
    SENSOR_GYRO_PERMANENT_ERROR(10.0),
    SENSOR_ACCELERATION_PASSING_ERROR(1.0),
    SENSOR_ACCELERATION_CONTINUOUS_ERROR(5.0),
    SENSOR_ACCELERATION_PERMANENT_ERROR(10.0),
    SENSOR_ALTITUDE_PASSING_ERROR(1.0),
    SENSOR_ALTITUDE_CONTINUOUS_ERROR(5.0),
    SENSOR_ALTITUDE_PERMANENT_ERROR(10.0),
    PROPELLER_LIGHT_DEMAGE(1.0),
    PROPELLER_INTERMEIDATE_DEMAGE(5.0),
    PROPELLER_HEAVY_DEMAGE(10.0),
    FRAME_LIGHT_DEMAGE(1.0),
    FRAME_INTERMEIDATE_DEMAGE(5.0),
    FRAME_HEAVY_DEMAGE(10.0),
    ESC_PASSING_ERROR(1.0),
    ESC_CONTINUOUS_ERROR(5.0),
    ESC_PERMANENT_ERROR(10.0),
    MCU_CONTROL_PASSING_ERROR(3.0),
    MCU_CONTROL_CONTINUOUS_ERROR(6.0),
    MCU_CONTROL_PERMANENT_ERROR(10.0),
    MCU_ARITHMETIC_PASSING_ERROR(3.0),
    MCU_ARITHMETIC_CONTINUOUS_ERROR(6.0),
    MCU_ARITHMETIC_PERMANENT_ERROR(10.0);

    private double point;

    ErrorType(double point){
        this.point = point;
    }

    public double getPoint(){
        return point;
    }
}
